owners:
  - number: '601153485936'
    name: FyteGoBrr
    # If you type '/owner' and if isCreator is true, this number will be shown as the owner
    isCreator: true
    # This field below will be displayed in vcard
    messages:
      - content: Hello 
        label: Greetings
    # if only one of the title or org is filled, it will not appear on the vcard
    title: creator 
    org: Midnight Vanguard
    emails: 
      - myyurax@gmail.com
    urls:
      - https://fytext.org
    
sticker:
  packname: Create stickers at wa.me/6285713964963
  author: ©2023 Metro Bot

donations: 
  gopay: 'no'
  dana: 'no'
  saweria: https://saweria.co/BochilGaming
  # other donations with format Record<string, string>

# level multiplier, higher is harder to go to the next level
multiplier: 30

emoticons:
  # not case-sensitive. All keys will be processed to lowercase
  exp: 💫
  level: 🧬
  money: 💸

community: https://chat.whatsapp.com/G9Z4h65krw7A0nOL1IgkMO